// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDawV74Jlx4sxOyR-Mu-8paBhgQuYlInJs',
    appId: '1:198143752083:web:94f42e57506d1fb8fe9a66',
    messagingSenderId: '198143752083',
    projectId: 'travel-expenses-879f9',
    authDomain: 'travel-expenses-879f9.firebaseapp.com',
    storageBucket: 'travel-expenses-879f9.appspot.com',
    measurementId: 'G-EWP6EK60XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnivhNoZmlck_ligmtsv3ZhViyM1XIAJ8',
    appId: '1:198143752083:android:84d511a4c6ce7176fe9a66',
    messagingSenderId: '198143752083',
    projectId: 'travel-expenses-879f9',
    storageBucket: 'travel-expenses-879f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUHbAWo9MBbuXF3M_76IyLHJ6ttCO7PlM',
    appId: '1:198143752083:ios:2a8b48a543d105d8fe9a66',
    messagingSenderId: '198143752083',
    projectId: 'travel-expenses-879f9',
    storageBucket: 'travel-expenses-879f9.appspot.com',
    iosBundleId: 'com.example.athangExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUHbAWo9MBbuXF3M_76IyLHJ6ttCO7PlM',
    appId: '1:198143752083:ios:2a8b48a543d105d8fe9a66',
    messagingSenderId: '198143752083',
    projectId: 'travel-expenses-879f9',
    storageBucket: 'travel-expenses-879f9.appspot.com',
    iosBundleId: 'com.example.athangExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDawV74Jlx4sxOyR-Mu-8paBhgQuYlInJs',
    appId: '1:198143752083:web:6db738f2b4c4ec66fe9a66',
    messagingSenderId: '198143752083',
    projectId: 'travel-expenses-879f9',
    authDomain: 'travel-expenses-879f9.firebaseapp.com',
    storageBucket: 'travel-expenses-879f9.appspot.com',
    measurementId: 'G-64WTHGJJLN',
  );
}
